### ISSUE TITLE
Allow functions that return (string, error)

### ISSUE THREAD

**Issue by stephenafamo** [a-h/templ#287]
Similar to `html/template`, it would be amazing to be able to also return an error from functions and then make the generated component return that error.

It would make the development experience much better for me.

**Comment by a-h** [comment]
I'm not really sure what you mean. Can you provide an example of how this would look in templ?

Are you talking about variable interpolation? So that instead of...

```
templ Template(value string) {
  <div>{ value }</div>
}
```

You'd have...

```
func getName(id int) (string, error) {
  record, err := db.Get(id)
  if err != nil {
    return err
  }
  return record.name, nil
}

templ Template(id int) {
  <div>{ getName(id) }</div>
}
```

If so, then I'd suggest an alternative design of constructing a "View Model" and passing that to your components. It separates the presentation and domain logic of your application which makes things easier to test and debug.

```go
type Handler struct {
  DB *DB
}

func (h Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
  var m InviteComponentViewModel
  m.Invites, err := h.DB.GetInvites(getUserIDFromContext(r.Context()))
  if err != nil {
     //TODO: Log error.
    m.ErrorMessage = "Failed to load invites, please try again"
  }
  teamInviteComponentModel(m).Render(r.Context(), w)
}

type InviteComponentViewModel struct {
  Invites []Invite
  ErrorMessage string
}

templ teamInviteComponent(model InviteComponentViewModel) {
	if len(model.Invites) > 0 {
		<div>You have { len(model.Invites) } pending invites</div>
               ... (more code to loop here)
	}
        if props.ErrorMessage != "" {
              ... (display error message)
        }
}
```

**Comment by stephenafamo** [comment]
I'm not suggesting something as crazy as making DB calls 😅. 

An example is the example in the documentation for using context 

```go
func GetTheme(ctx context.Context) string {
	if theme, ok := ctx.Value(themeContextKey).(string); ok {
		return theme
	}
	return ""
}
```

It would be convenient to be able to return an error from places like this.


```go
func GetTheme(ctx context.Context) (string, error) {
	if theme, ok := ctx.Value(themeContextKey).(string); ok {
		return theme
	}
	return errors.New("no theme in context")
}

**Comment by a-h** [comment]
Sorry, that's not enough detail for me to understand what you're thinking about.

Can you show how you would want to use that function in templ? Something like this, something else?

```templ
templ Template(id int) {
  { theme, err := getTheme(ctx) }
  if err != nil {
    return err
  }
  @display(theme)
}
```

**Comment by a-h** [comment]
I've also updated the docs to include a new page on view models - https://templ.guide/core-concepts/view-models

**Comment by stephenafamo** [comment]
I mean using it the same way functions that return plain strings are used:

```
func getName(id int) (string, error) {
   return "hello", nil
}

templ Template(id int) {
  <div>{ getName(id) }</div>
}
```

However, when the template is compiled, it adds an `if err != nil` block

**Comment by a-h** [comment]
OK! Now I understand.

Now that Go generics are in play, it is possible to maintain compile time checks for interpolated variables.

At the moment, templates expect a string value, but by adding a helper function in the middle with a type constraint, it could be possible to call the functions etc.

https://go.dev/play/p/SN_PmK8sdln

It may be possible to move the type switch to generation time to avoid adding anything to the runtime cost, but I haven't thought about how though.

**Comment by stephenafamo** [comment]
I don't think generics solves this. Because it is not always going to be `func() (string, error)` only that the return type is `(string, error)`. For example, the function could be `func(context.Context, id int, role string) (string, error)`

I believe there is no way around this without reflection.

**Comment by a-h** [comment]
Got an example of what you mean?

**Comment by a-h** [comment]
Could be done with a variadic function used to normalise `(string)` and `(string, error)` values.

https://go.dev/play/p/9LfkPx4o-Lo

**Comment by stephenafamo** [comment]
That's pretty neat!

**Comment by a-h** [comment]
It doesn't seem to affect performance from the limited testing I've done. I'd want to make sure there's no serious performance regression.

As per contributing.md, would need some docs and appropriate testing of the feature.

**Comment by a-h** [comment]
I'd love a PR if you're up for it. I haven't considered / checked the following:

* Will the LSP have any issues? I think not, but I haven't tested it.
* What about parameters in CSS values? Should they be able to accept the results of a function that is `(string, error)` - I think so, for completeness.
* The tests need to cover both successful returns of a string, and returning errors.

**Comment by stephenafamo** [comment]
Sent in PR #299. No docs about it yet though.

> Will the LSP have any issues? I think not, but I haven't tested it.

I tested it locally, works fine. Not sure if there are tests for the LSP


> What about parameters in CSS values? Should they be able to accept the results of a function that is `(string, error)` - I think so, for completeness.

Not implemented yet. I'll get to it soon

> The tests need to cover both successful returns of a string, and returning errors.

Done 👍🏾

**Comment by stephenafamo** [comment]
The generated code for CSS components does not return an error.  
So allowing error-able expressions in CSS components  would mean changing the signature of the generated code. 
from: `func componentName() templ.CSSClass`   
to: `func componentName() (templ.CSSClass, error)`. 

his will affect a bunch of other things, I think it should be a separate PR.

**Comment by stephenafamo** [comment]
Added docs. Ready to merge.

**Comment by joerdav** [comment]
I think there should be ideally some more thought into this one, or maybe a future enhancement. My concern is that it encourages not handling errors.

Personally, I would always call functions that could error before rendering the template to simplify rendering.

But that's my personal preference so doesn't matter as much. Though if we're doing this I think the error returned should be useful. At the moment if you called `strconv.Atoi("a")` you would get an "invalid syntax" error, which would be useful for very simple templates, but if you had a large template with many nested components, and many strconv calls, you may struggle to find the origin.

Maybe giving a way to wrap errors would help, or automatically wrapping errors with context of the component it was called from.

**Comment by stephenafamo** [comment]
> if you had a large template with many nested components, and many strconv calls, you may struggle to find the origin.

I see the issue... tracking down the source of an error. Perhaps it makes sense to have a version of `writeErrorHandler` that wraps the error. e.g. `writeWrappedErrorHandler(indentLevel int, info string)`.

**Comment by a-h** [comment]
Good point @joerdav!

The string expression already has a position in the templ source code within it, so perhaps the generator could use that to wrap any error that's returned with the position in the template.

https://github.com/a-h/templ/blob/6c411018048a7aa35a275caddc5c3c1222283293/parser/v2/types.go#L1000-L1004

```go
var templ_7745c5c3_Var2 string
templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.EscapeStringErrs(getValue())
if templ_7745c5c3_Err != nil {
	return fmt.Errorf("<template_name>: expression returned an error at line %d, col %d: %w", 123, 456, templ_7745c5c3_Err)
}
```

Instead of using `fmt.Errorf()` could use an error type instead if unwrapping that error is hard.

**Comment by stephenafamo** [comment]
> Instead of using `fmt.Errorf()` could use an error type instead if unwrapping that error is hard.

I think using a custom error type would be great. But just wrapping the error would be good too.

**Comment by stephenafamo** [comment]
Will the plan be to rewrite the existing `writeErrorHandler` to include extra error information?

**Comment by joerdav** [comment]
@stephenafamo I think that would be the solution yes. Though my recommendation still would be to resolve errors before entering templates, as to not result in partially rendered templates if an error occurs.

**Comment by a-h** [comment]
I updated the PR to include a custom error in the templ runtime. If a string expression returns an error, `templ.Render`, will return a `templ.Error`: https://github.com/a-h/templ/pull/299/commits/a4b7bc87b08b870d8e11c027cfcc2641e919ef67

```go
// Error returned during template rendering.
type Error struct {
	Err error
	// Line index of the error.
	Line int
	// Col index of the error.
	Col int
}

func (e Error) Error() string {
	return fmt.Sprintf("template error at line %d, col %d: %v", e.Line, e.Col, e.Err)
}

func (e Error) Unwrap() error {
	return e.Err
}
```

I totally agree that it's better to create a view model to collect the data that the template needs up-front than to start connecting to databases, or do anything else than cause errors. I added a page at https://templ.guide/core-concepts/view-models/ to get that concept across.

Happy with that @joerdav?

**Comment by stephenafamo** [comment]
Is the ready to be merged now? Is there anything else that needs to be done?

**Comment by joerdav** [comment]
I'm still not quite sure this helps, although it's an improvement.

Imagine you were doing some template composition that spanned multiple files. 

You might have a call stack of templates which without it you wouldn't know which file `line` and `col` were referencing.

I suppose a solution may be to include the template function name? Or a file name at the very least?

**Comment by a-h** [comment]
Ah, good point @joerdav. I don't know why I didn't think of that(!)

The `writeTemplate` function knows the name of the template during generation, so when it calls `writeNodes`, it could pass that as a parameter. So, the error message would be like this:

```
templateName: template error at line 123, col 456: <error>
```

But, that's still not very useful, because you might call each one of your templates `Template()` or something, and have one template per package... so.

To add the filename, it would need to relative to `go.mod` file, since otherwise, it would potentially change between machines, or leak usernames etc. To sort that, the `TemplateFile` type could have a `FileName` field added to it. `TemplateFile` is already a field in the to the `Generator` struct, so no changes required there, and it's accessible from any method in the generator.

So, it would be a case of adding the file name, and template name to the error type, and populating them in the generator.

```
./github.com/project/name/templatepackage/templates.templ: templateName: template error at line 123, col 456: <error>
```

**Comment by stephenafamo** [comment]
What would be the best way to proceed now? @a-h

**Comment by a-h** [comment]
Next step would be to add the file name and template name to the error type.

1. Add a `WithFileName` function to the `generator.go` as per https://github.com/a-h/templ/blob/ac11ed2f254038c6527df78e5b3f5d751c3e92e7/generator/generator.go#L22-L27 and update the CLI generate command to use it.
2. Update https://github.com/a-h/templ/blob/ac11ed2f254038c6527df78e5b3f5d751c3e92e7/generator/generator.go#L1244 to the optional file name, and the existing package name field to populate the error.

I don't think it's much work, just haven't had chance to work on it yet. This will get merged, just a little more to go.
